services:
  db:
    container_name: product-name-db
    image: postgres:16.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"

  backend:
    container_name: product-name-backend
    build: .
    volumes:
      - .:/app
      # 仮想環境はコピーしなくて良いのでダミーを作る。
      - dummy:/app/.venv
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file: .env
    command: ["poetry", "run", "uvicorn", "app.router.main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--reload-dir", "/app"]

  localstack:
    container_name: product-name-localstack
    image: localstack/localstack
    environment:
      SERVICES: s3
      DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  dummy:
